init:
	npm init -y
	npm i -D typescript @types/node eslint @rocketseat/eslint-config
	npx tsc --init
	npm i -D eslint @rocketseat/eslint-config
	npm i fastify
	npm i dotenv knex sqlite3 zod
init-tests:
	npm i -D @types/supertest
	npm i vitest